backbone: 'DNN'
OneHotMatrix: 0
data_path: '../datasets/amazon-book_clean/'
dataset: 'amazon-book_clean'
lr: 5e-5
weight_decay: 0
batch_size: 400
dims: 1000
emb_size: 10
mean_type: x0
steps: 5
noise_scale: 0.0001
noise_min: 0.0005
noise_max: 0.005
sampling_steps: 0
reweight: 1
log_name: log
round: 1
gpu: 0
discrete: 0.98
random_seed: 0
