
backbone: 'DNNOneHotEmbeddingGCN'
OneHotMatrix: 2
data_path: '../datasets/amazon-book_clean/'
dataset: 'amazon-book_clean'
lr: 5e-5
weight_decay: 0
batch_size: 400
dims: [1024]
emb_size: 10
mean_type: x0
steps: 5
noise_scale: 0.0001
log_name: log
gpu: 0
random_seed: 0
