backbone: 'DNNOneHotEmbeddingGCN'
OneHotMatrix: 2
data_path: '../datasets/yelp_clean/'
dataset: 'yelp_clean'
sampling_steps: 0
steps: 30
lr: 0.00001
weight_decay: 0.0
batch_size: 64
dims: [1000]
noise_scale: 0.01
noise_min: 0.001
noise_max: 0.01
discrete: 0.999